# Generated by Django 4.1.7 on 2023-02-25 14:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_commentsystem_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsystem',
            name='body',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
