# Generated by Django 4.1.7 on 2023-02-25 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_commentsystem_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentsystem',
            name='comment',
        ),
        migrations.AddField(
            model_name='commentsystem',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_comment', to='blog.commentsystem'),
        ),
    ]
